all: second_2_3 count mycp_2_7 frontdesk_2_10_11 fileopen_2_14 io_2_15

second_2_3: Second_3.c
	gcc Second_3.c -o second_2_3

count: Count_2_5.c
	gcc Count_2_5.c -o count

mycp_2_7: mycp_2_7.c
	gcc mycp_2_7.c -o mycp_2_7

frontdesk_2_10_11: frontdesk_2_10_11.c
	gcc frontdesk_2_10_11.c -o frontdesk_2_10_11

fileopen_2_14: fileopen_2_14.c
	gcc fileopen_2_14.c -o fileopen_2_14

io_2_15: io_2_15.c
	gcc io_2_15.c -o io_2_15